name: pyoperon
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cxx-compiler
  - clangxx
  - cmake
  - eigen
  - git
  - make
  - nanobind
  - pkg-config
  - scikit-build-core
  - xxhash
  - zstd
  - zstd-static
  - zlib
  - cmake-package-check
