[tool.poetry]
build = "build.py"
name = "pyoperon"
version = "0.3.1"
description = "Scikit-learn module and python bindings and for the Operon library"
readme = "README.md"
repository = "https://github.com/heal-research/pyoperon"
homepage = "https://github.com/heal-research/pyoperon"
license = "MIT"
authors = [ "Bogdan Burlacu <bogdan.burlacu@pm.me>" ]

[tool.poetry.dependencies]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/heal-research/pyoperon/issues"
