name: build-macos

on:
  push:
    branches: [ cpp20 ]
  pull_request:
    branches: [ cpp20 ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  mamba-build:
    strategy:
      matrix:
        version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
        os: [ macos-11, macos-12, macos-13 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment from environment.yml
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: >-
            python=${{ matrix.version }}
          cache-environment: true

      - name: Run the build script
        shell: bash -l {0}
        run: |
          export CC=clang
          export CXX=clang++
          bash script/dependencies.sh # install dependencies
          python setup.py bdist_wheel -- --preset build-osx # build the wheel

      - name: 'Build wheel'
        uses: actions/upload-artifact@v3
        with:
          name: pyoperon-wheel
          path: dist/*.whl
          retention-days: 90